## Cross Validation
### Evaluating model performance
Sometimes we get into the dilemma of each machine learning model should I use to solve a particular problem!!. For example we looked at the Iris flower dataset problem using(decision tree, random forest,logistic regression and SVM) but each model out of these is the best? Cross validation is technique that helps with this, it allows us to  evaluate the performance of a model.

#### Options for machine learning
1) use all available data for training and and test on same datset.

2) Split available dataste into training and test sets

3) K fold cross validation: Take for instance we have 100 samples, we will divide this 100 samples into 5 folds, each containing 20 samples then we run multiple iterations on the folds. We will then average of all the scores.

In [2]:
# Evaluating the performance of different models on the hand written dataset using the k-fold method

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import warnings
warnings.filterwarnings("ignore")

digits = load_digits()


In [3]:
# The distribution of samples in X_train, y_train is not uniform, we can not judge all the models based on one iteration
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, 
                                                    digits.target,
                                                    test_size=0.3)

In [4]:
# Using an individual classifier
lr = LogisticRegression()
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9685185185185186

In [5]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9925925925925926

In [6]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.975925925925926

In [7]:
# KFold explanation (How does KFold works)
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [12]:
for train_index, test_index in kf.split([1, 2, 3, 4, 5, 6, 7, 8, 9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [13]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [14]:
get_score(LogisticRegression(), X_train, X_test, y_train, y_test)

C:\Users\TEMITOPE\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9648148148148148

In [15]:
get_score(SVC(), X_train, X_test, y_train, y_test)

0.9925925925925926

In [16]:
# StratifiedKFold divides the classification category in a uniform way when we try to separate out the folds
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3) # Data scientist are fond of using 10

In [18]:
digits.data.shape

(1797, 64)

In [19]:
score_l = []
score_svm = []
score_rf = []

for train_index, test_index in kf.split(digits.data):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                        digits.target[train_index], digits.target[test_index]
    score_l.append(get_score(LogisticRegression(), X_train, X_test, y_train, y_test))
    score_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    score_rf.append(get_score(RandomForestClassifier(n_estimators=20), X_train, X_test, y_train, y_test))
    
    
    
    

C:\Users\TEMITOPE\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\TEMITOPE\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n

In [20]:
score_l

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [21]:
score_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [22]:
score_rf

[0.8964941569282137, 0.9415692821368948, 0.9315525876460768]

In [24]:
# The cross_val_score form sklearn does thesame process
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(), digits.data, digits.target)

C:\Users\TEMITOPE\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\TEMITOPE\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [28]:
cross_val_score(SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [29]:
cross_val_score(RandomForestClassifier(), digits.data, digits.target)

array([0.94166667, 0.9       , 0.96657382, 0.96100279, 0.93036212])